<?php

// WordPress title tag management
add_theme_support('title-tag');

// ########## MENUS ##########

// Enable menus feature
add_theme_support('menus');

// Define menus locations
    register_nav_menus(
        array(
            'main-navigation' => __( 'Main Navigation' ),
            'footer' => __( 'Footer Navigation' ) // Assurez-vous que l'emplacement 'footer' est bien enregistré
        )
    );

    add_action( 'acf/include_fields', function() {
        if ( ! function_exists( 'acf_add_local_field_group' ) ) {
            return;
        }
    
        acf_add_local_field_group( array(
        'key' => 'group_6686696b24f5e',
        'title' => 'Accueil',
        'fields' => array(
            array(
                'key' => 'field_6686696c5911e',
                'label' => 'Texte du header',
                'name' => 'home__header_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66866ada58ee4',
                'label' => 'Sous Titre du header',
                'name' => 'home__header_subtitle',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66866b0758ee5',
                'label' => 'Image de fond',
                'name' => 'home__header_background_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_668673317ab59',
                'label' => 'Les menus du moment',
                'name' => 'home__header_menu',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Ajouter un élément',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_668673d27ab5a',
                        'label' => 'Nom du menu',
                        'name' => 'name',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_668673317ab59',
                    ),
                    array(
                        'key' => 'field_668674117ab5b',
                        'label' => 'Image du menu',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                        'parent_repeater' => 'field_668673317ab59',
                    ),
                ),
            ),
            array(
                'key' => 'field_6686a04875711',
                'label' => 'Image présentation cuisine méditerranéenne',
                'name' => 'body__content_first_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_66869f2e7570e',
                'label' => 'Titre cuisine méditerranéenne',
                'name' => 'body__content_first_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6686a15c8a61a',
                'label' => 'Sous-titre cuisine méditerranéenne',
                'name' => 'body__content_first_subtitle',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_66869f9e7570f',
                'label' => 'Image présentation sur les menus végétariens',
                'name' => 'body__content_second_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6686a0c78a618',
                'label' => 'Titre menus végétariens',
                'name' => 'body__content_second_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6686a18a8a61b',
                'label' => 'Sous-titres menus végétariens',
                'name' => 'body__content_second_subtitle',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_6686a1ba8a61c',
                'label' => 'Image Héberger événement',
                'name' => 'body__content_third_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6686a2218a61d',
                'label' => 'Titre Héberger événement',
                'name' => 'body__content_third_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6686a2228a61e',
                'label' => 'Sous-titre Héberger événement',
                'name' => 'body__content_third_subtitle',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_6686a2768a61f',
                'label' => 'Image Livraison',
                'name' => 'body__content_fourth_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6686a2cf8a620',
                'label' => 'Titre livraison',
                'name' => 'body__content_fourth_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6686a2e18a621',
                'label' => 'Sous-titre',
                'name' => 'body__content_fourth_subtitle',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_6687c899b7cc0',
                'label' => 'Les menus phares',
                'name' => 'body__content_menu_phare',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_669121a9d138a',
                'label' => 'Voir les menus par pays',
                'name' => 'body__content_menu_cat',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_type',
                    'operator' => '==',
                    'value' => 'front_page',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
    
        acf_add_local_field_group( array(
        'key' => 'group_668f8cce5a150',
        'title' => 'Footer_Fields',
        'fields' => array(
            array(
                'key' => 'field_668f8ccf157c5',
                'label' => 'Facebook',
                'name' => 'footer__facebook_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_668faaa3bd7a6',
                'label' => 'Instagram',
                'name' => 'footer__instagram_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6690e38c28e19',
                'label' => 'Youtube',
                'name' => 'footer__youtube_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'nav_menu',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
    
        acf_add_local_field_group( array(
        'key' => 'group_6687b7e91bf89',
        'title' => 'Menus phares',
        'fields' => array(
            array(
                'key' => 'field_6687bed35de13',
                'label' => 'Image du menu',
                'name' => 'menu_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6687b8b936fbb',
                'label' => 'Nom du menu',
                'name' => 'menu_name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6687b7e9d6351',
                'label' => 'Prix du menu',
                'name' => 'menu_price',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6687b8cc36fbc',
                'label' => 'Description du menu',
                'name' => 'menu_desc',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_6687e6610ebfc',
                'label' => 'Bouton',
                'name' => 'menu_cta_button',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6687e67a0ebfd',
                        'label' => 'Texte Bouton',
                        'name' => 'menu_cta_button_text',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Voir plus',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_6687e68c0ebfe',
                        'label' => 'Lien du bouton',
                        'name' => 'menu_cta_button_link',
                        'aria-label' => '',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'menu_phare',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
    } );
    
    function cptui_register_my_cpts() {

        /**
         * Post Type: Menus phares.
         */
    
        $labels = [
            "name" => esc_html__( "Menus phares", "custom-post-type-ui" ),
            "singular_name" => esc_html__( "Menu phare", "custom-post-type-ui" ),
            "menu_name" => esc_html__( "Menus phares", "custom-post-type-ui" ),
            "all_items" => esc_html__( "Tous les Menus phares", "custom-post-type-ui" ),
            "add_new" => esc_html__( "Ajouter un nouveau", "custom-post-type-ui" ),
            "add_new_item" => esc_html__( "Ajouter un nouveau Menu phare", "custom-post-type-ui" ),
            "edit_item" => esc_html__( "Modifier Menu phare", "custom-post-type-ui" ),
            "new_item" => esc_html__( "Nouveau Menu phare", "custom-post-type-ui" ),
            "view_item" => esc_html__( "Voir Menu phare", "custom-post-type-ui" ),
            "view_items" => esc_html__( "Voir Menus phares", "custom-post-type-ui" ),
            "search_items" => esc_html__( "Recherche de Menus phares", "custom-post-type-ui" ),
            "not_found" => esc_html__( "Aucun Menus phares trouvé", "custom-post-type-ui" ),
            "not_found_in_trash" => esc_html__( "Aucun Menus phares trouvé dans la corbeille", "custom-post-type-ui" ),
            "parent" => esc_html__( "Menu phare parent :", "custom-post-type-ui" ),
            "featured_image" => esc_html__( "Image mise en avant pour ce Menu phare", "custom-post-type-ui" ),
            "set_featured_image" => esc_html__( "Définir l’image mise en avant pour ce Menu phare", "custom-post-type-ui" ),
            "remove_featured_image" => esc_html__( "Retirer l’image mise en avant pour ce Menu phare", "custom-post-type-ui" ),
            "use_featured_image" => esc_html__( "Utiliser comme image mise en avant pour ce Menu phare", "custom-post-type-ui" ),
            "archives" => esc_html__( "Archives de Menu phare", "custom-post-type-ui" ),
            "insert_into_item" => esc_html__( "Insérer dans Menu phare", "custom-post-type-ui" ),
            "uploaded_to_this_item" => esc_html__( "Téléverser sur ce Menu phare", "custom-post-type-ui" ),
            "filter_items_list" => esc_html__( "Filtrer la liste de Menus phares", "custom-post-type-ui" ),
            "items_list_navigation" => esc_html__( "Navigation de liste de Menus phares", "custom-post-type-ui" ),
            "items_list" => esc_html__( "Liste de Menus phares", "custom-post-type-ui" ),
            "attributes" => esc_html__( "Attributs de Menus phares", "custom-post-type-ui" ),
            "name_admin_bar" => esc_html__( "Menu phare", "custom-post-type-ui" ),
            "item_published" => esc_html__( "Menu phare publié", "custom-post-type-ui" ),
            "item_published_privately" => esc_html__( "Menu phare publié en privé.", "custom-post-type-ui" ),
            "item_reverted_to_draft" => esc_html__( "Menu phare repassé en brouillon.", "custom-post-type-ui" ),
            "item_trashed" => esc_html__( "Menu phare mis à la corbeille.", "custom-post-type-ui" ),
            "item_scheduled" => esc_html__( "Menu phare planifié", "custom-post-type-ui" ),
            "item_updated" => esc_html__( "Menu phare mis à jour.", "custom-post-type-ui" ),
            "parent_item_colon" => esc_html__( "Menu phare parent :", "custom-post-type-ui" ),
        ];
    
        $args = [
            "label" => esc_html__( "Menus phares", "custom-post-type-ui" ),
            "labels" => $labels,
            "description" => "",
            "public" => true,
            "publicly_queryable" => true,
            "show_ui" => true,
            "show_in_rest" => true,
            "rest_base" => "",
            "rest_controller_class" => "WP_REST_Posts_Controller",
            "rest_namespace" => "wp/v2",
            "has_archive" => false,
            "show_in_menu" => true,
            "show_in_nav_menus" => true,
            "delete_with_user" => false,
            "exclude_from_search" => false,
            "capability_type" => "post",
            "map_meta_cap" => true,
            "hierarchical" => false,
            "can_export" => false,
            "rewrite" => [ "slug" => "menu_phare", "with_front" => true ],
            "query_var" => true,
            "supports" => [ "title" ],
            "show_in_graphql" => false,
        ];
    
        register_post_type( "menu_phare", $args );
    }
    
    add_action( 'init', 'cptui_register_my_cpts' );
    function cptui_register_my_cpts_menu_phare() {

        /**
         * Post Type: Menus phares.
         */
    
        $labels = [
            "name" => esc_html__( "Menus phares", "custom-post-type-ui" ),
            "singular_name" => esc_html__( "Menu phare", "custom-post-type-ui" ),
            "menu_name" => esc_html__( "Menus phares", "custom-post-type-ui" ),
            "all_items" => esc_html__( "Tous les Menus phares", "custom-post-type-ui" ),
            "add_new" => esc_html__( "Ajouter un nouveau", "custom-post-type-ui" ),
            "add_new_item" => esc_html__( "Ajouter un nouveau Menu phare", "custom-post-type-ui" ),
            "edit_item" => esc_html__( "Modifier Menu phare", "custom-post-type-ui" ),
            "new_item" => esc_html__( "Nouveau Menu phare", "custom-post-type-ui" ),
            "view_item" => esc_html__( "Voir Menu phare", "custom-post-type-ui" ),
            "view_items" => esc_html__( "Voir Menus phares", "custom-post-type-ui" ),
            "search_items" => esc_html__( "Recherche de Menus phares", "custom-post-type-ui" ),
            "not_found" => esc_html__( "Aucun Menus phares trouvé", "custom-post-type-ui" ),
            "not_found_in_trash" => esc_html__( "Aucun Menus phares trouvé dans la corbeille", "custom-post-type-ui" ),
            "parent" => esc_html__( "Menu phare parent :", "custom-post-type-ui" ),
            "featured_image" => esc_html__( "Image mise en avant pour ce Menu phare", "custom-post-type-ui" ),
            "set_featured_image" => esc_html__( "Définir l’image mise en avant pour ce Menu phare", "custom-post-type-ui" ),
            "remove_featured_image" => esc_html__( "Retirer l’image mise en avant pour ce Menu phare", "custom-post-type-ui" ),
            "use_featured_image" => esc_html__( "Utiliser comme image mise en avant pour ce Menu phare", "custom-post-type-ui" ),
            "archives" => esc_html__( "Archives de Menu phare", "custom-post-type-ui" ),
            "insert_into_item" => esc_html__( "Insérer dans Menu phare", "custom-post-type-ui" ),
            "uploaded_to_this_item" => esc_html__( "Téléverser sur ce Menu phare", "custom-post-type-ui" ),
            "filter_items_list" => esc_html__( "Filtrer la liste de Menus phares", "custom-post-type-ui" ),
            "items_list_navigation" => esc_html__( "Navigation de liste de Menus phares", "custom-post-type-ui" ),
            "items_list" => esc_html__( "Liste de Menus phares", "custom-post-type-ui" ),
            "attributes" => esc_html__( "Attributs de Menus phares", "custom-post-type-ui" ),
            "name_admin_bar" => esc_html__( "Menu phare", "custom-post-type-ui" ),
            "item_published" => esc_html__( "Menu phare publié", "custom-post-type-ui" ),
            "item_published_privately" => esc_html__( "Menu phare publié en privé.", "custom-post-type-ui" ),
            "item_reverted_to_draft" => esc_html__( "Menu phare repassé en brouillon.", "custom-post-type-ui" ),
            "item_trashed" => esc_html__( "Menu phare mis à la corbeille.", "custom-post-type-ui" ),
            "item_scheduled" => esc_html__( "Menu phare planifié", "custom-post-type-ui" ),
            "item_updated" => esc_html__( "Menu phare mis à jour.", "custom-post-type-ui" ),
            "parent_item_colon" => esc_html__( "Menu phare parent :", "custom-post-type-ui" ),
        ];
    
        $args = [
            "label" => esc_html__( "Menus phares", "custom-post-type-ui" ),
            "labels" => $labels,
            "description" => "",
            "public" => true,
            "publicly_queryable" => true,
            "show_ui" => true,
            "show_in_rest" => true,
            "rest_base" => "",
            "rest_controller_class" => "WP_REST_Posts_Controller",
            "rest_namespace" => "wp/v2",
            "has_archive" => false,
            "show_in_menu" => true,
            "show_in_nav_menus" => true,
            "delete_with_user" => false,
            "exclude_from_search" => false,
            "capability_type" => "post",
            "map_meta_cap" => true,
            "hierarchical" => false,
            "can_export" => false,
            "rewrite" => [ "slug" => "menu_phare", "with_front" => true ],
            "query_var" => true,
            "supports" => [ "title" ],
            "show_in_graphql" => false,
        ];
    
        register_post_type( "menu_phare", $args );
    }
    
    add_action( 'init', 'cptui_register_my_cpts_menu_phare' );

    function cptui_register_my_taxes() {

        /**
         * Taxonomy: pays.
         */
    
        $labels = [
            "name" => esc_html__( "pays", "custom-post-type-ui" ),
            "singular_name" => esc_html__( "pays", "custom-post-type-ui" ),
            "menu_name" => esc_html__( "pays", "custom-post-type-ui" ),
            "all_items" => esc_html__( "Tous les pays", "custom-post-type-ui" ),
            "edit_item" => esc_html__( "Modifier pays", "custom-post-type-ui" ),
            "view_item" => esc_html__( "Voir pays", "custom-post-type-ui" ),
            "update_item" => esc_html__( "Mettre à jour le nom de pays", "custom-post-type-ui" ),
            "add_new_item" => esc_html__( "Ajouter un nouveau pays", "custom-post-type-ui" ),
            "new_item_name" => esc_html__( "Nom du nouveau pays", "custom-post-type-ui" ),
            "parent_item" => esc_html__( "Parent dpays", "custom-post-type-ui" ),
            "parent_item_colon" => esc_html__( "pays parent :", "custom-post-type-ui" ),
            "search_items" => esc_html__( "Recherche de pays", "custom-post-type-ui" ),
            "popular_items" => esc_html__( "pays populaires", "custom-post-type-ui" ),
            "separate_items_with_commas" => esc_html__( "Séparer les pays avec des virgules", "custom-post-type-ui" ),
            "add_or_remove_items" => esc_html__( "Ajouter ou supprimer des pays", "custom-post-type-ui" ),
            "choose_from_most_used" => esc_html__( "Choisir parmi les pays les plus utilisés", "custom-post-type-ui" ),
            "not_found" => esc_html__( "Aucun pays trouvé", "custom-post-type-ui" ),
            "no_terms" => esc_html__( "Aucun pays", "custom-post-type-ui" ),
            "items_list_navigation" => esc_html__( "Navigation de liste de pays", "custom-post-type-ui" ),
            "items_list" => esc_html__( "Liste de pays", "custom-post-type-ui" ),
            "back_to_items" => esc_html__( "Retourner à pays", "custom-post-type-ui" ),
            "name_field_description" => esc_html__( "Le nom tel qu’il apparaîtra sur votre site.", "custom-post-type-ui" ),
            "parent_field_description" => esc_html__( "Assigner un terme parent pour créer une hiérarchie. Le terme « Jazz », par exemple, serait le parent de « Bebop » et « Big Band ».", "custom-post-type-ui" ),
            "slug_field_description" => esc_html__( "Le « slug » est une version du nom compatible avec les URL. Il est généralement entièrement en minuscules et contient uniquement des lettres, chiffres et tirets.", "custom-post-type-ui" ),
            "desc_field_description" => esc_html__( "La description n’est pas mise en évidence par défaut ; toutefois, certains thèmes peuvent l’afficher.", "custom-post-type-ui" ),
        ];
    
        
        $args = [
            "label" => esc_html__( "pays", "custom-post-type-ui" ),
            "labels" => $labels,
            "public" => true,
            "publicly_queryable" => true,
            "hierarchical" => true,
            "show_ui" => true,
            "show_in_menu" => true,
            "show_in_nav_menus" => true,
            "query_var" => true,
            "rewrite" => [ 'slug' => 'pays', 'with_front' => true, ],
            "show_admin_column" => false,
            "show_in_rest" => true,
            "show_tagcloud" => false,
            "rest_base" => "pays",
            "rest_controller_class" => "WP_REST_Terms_Controller",
            "rest_namespace" => "wp/v2",
            "show_in_quick_edit" => false,
            "sort" => false,
            "show_in_graphql" => false,
        ];
        register_taxonomy( "pays", [ "menu_phare" ], $args );
    }
    add_action( 'init', 'cptui_register_my_taxes' );

    function cptui_register_my_taxes_pays() {

        /**
         * Taxonomy: pays.
         */
    
        $labels = [
            "name" => esc_html__( "pays", "custom-post-type-ui" ),
            "singular_name" => esc_html__( "pays", "custom-post-type-ui" ),
            "menu_name" => esc_html__( "pays", "custom-post-type-ui" ),
            "all_items" => esc_html__( "Tous les pays", "custom-post-type-ui" ),
            "edit_item" => esc_html__( "Modifier pays", "custom-post-type-ui" ),
            "view_item" => esc_html__( "Voir pays", "custom-post-type-ui" ),
            "update_item" => esc_html__( "Mettre à jour le nom de pays", "custom-post-type-ui" ),
            "add_new_item" => esc_html__( "Ajouter un nouveau pays", "custom-post-type-ui" ),
            "new_item_name" => esc_html__( "Nom du nouveau pays", "custom-post-type-ui" ),
            "parent_item" => esc_html__( "Parent dpays", "custom-post-type-ui" ),
            "parent_item_colon" => esc_html__( "pays parent :", "custom-post-type-ui" ),
            "search_items" => esc_html__( "Recherche de pays", "custom-post-type-ui" ),
            "popular_items" => esc_html__( "pays populaires", "custom-post-type-ui" ),
            "separate_items_with_commas" => esc_html__( "Séparer les pays avec des virgules", "custom-post-type-ui" ),
            "add_or_remove_items" => esc_html__( "Ajouter ou supprimer des pays", "custom-post-type-ui" ),
            "choose_from_most_used" => esc_html__( "Choisir parmi les pays les plus utilisés", "custom-post-type-ui" ),
            "not_found" => esc_html__( "Aucun pays trouvé", "custom-post-type-ui" ),
            "no_terms" => esc_html__( "Aucun pays", "custom-post-type-ui" ),
            "items_list_navigation" => esc_html__( "Navigation de liste de pays", "custom-post-type-ui" ),
            "items_list" => esc_html__( "Liste de pays", "custom-post-type-ui" ),
            "back_to_items" => esc_html__( "Retourner à pays", "custom-post-type-ui" ),
            "name_field_description" => esc_html__( "Le nom tel qu’il apparaîtra sur votre site.", "custom-post-type-ui" ),
            "parent_field_description" => esc_html__( "Assigner un terme parent pour créer une hiérarchie. Le terme « Jazz », par exemple, serait le parent de « Bebop » et « Big Band ».", "custom-post-type-ui" ),
            "slug_field_description" => esc_html__( "Le « slug » est une version du nom compatible avec les URL. Il est généralement entièrement en minuscules et contient uniquement des lettres, chiffres et tirets.", "custom-post-type-ui" ),
            "desc_field_description" => esc_html__( "La description n’est pas mise en évidence par défaut ; toutefois, certains thèmes peuvent l’afficher.", "custom-post-type-ui" ),
        ];
    
        
        $args = [
            "label" => esc_html__( "pays", "custom-post-type-ui" ),
            "labels" => $labels,
            "public" => true,
            "publicly_queryable" => true,
            "hierarchical" => true,
            "show_ui" => true,
            "show_in_menu" => true,
            "show_in_nav_menus" => true,
            "query_var" => true,
            "rewrite" => [ 'slug' => 'pays', 'with_front' => true, ],
            "show_admin_column" => false,
            "show_in_rest" => true,
            "show_tagcloud" => false,
            "rest_base" => "pays",
            "rest_controller_class" => "WP_REST_Terms_Controller",
            "rest_namespace" => "wp/v2",
            "show_in_quick_edit" => false,
            "sort" => false,
            "show_in_graphql" => false,
        ];
        register_taxonomy( "pays", [ "menu_phare" ], $args );
    }
    add_action( 'init', 'cptui_register_my_taxes_pays' );